/**
 * Generated by the Babylon.JS Editor v4.0.0-beta.7
 */
import { Scene } from "@babylonjs/core";
/**
 * Defines the map of all available scripts in the project.
 */
export declare const scriptsMap: {
    "src/scenes/scene/ball.ts": any;
    "src/scenes/scene/bloc.ts": any;
    "src/scenes/scene/bloc1.1.ts": any;
    "src/scenes/scene/blocMoove.ts": any;
    "src/scenes/scene/camera.ts": any;
    "src/scenes/scene/shark.ts": any;
    "src/scenes/scene/target.ts": any;
    "src/scenes/scene/time.ts": any;
};
/**
 * Works as an helper, this will:
 * = attach scripts on objects.
 * @param scene the scene to attach scripts, etc.
 */
export declare function runScene(scene: Scene, rootUrl?: string): Promise<void>;
